<AdminRfidScreen>:
    name: "admin_rfid_screen"
    md_bg_color: 0.95, 0.96, 0.98, 1  # สีพื้นหลังเทาอมฟ้าอ่อนตามธีมตู้

    MDBoxLayout:
        orientation: "vertical"
        padding: "24dp"
        spacing: "16dp"

        # --- ส่วนของ Header ด้านบน ---
        MDBoxLayout:
            size_hint_y: None
            height: "64dp"
            md_bg_color: 1, 1, 1, 1
            radius: [16, 16, 16, 16]
            padding: ["16dp", "0dp"]
            spacing: "16dp"
            elevation: 1
            shadow_softness: 12

            MDIconButton:
                icon: "arrow-left"
                pos_hint: {"center_y": .5}
                theme_icon_color: "Custom"
                icon_color: 0.06, 0.11, 0.26, 1  # สีน้ำเงินเข้มตามธีมของคุณ
                on_release: root.go_back_home()

            MDLabel:
                text: "ผูกบัตร RFID พนักงาน"
                font_style: "H6"
                font_name: "Thai"
                bold: True
                theme_text_color: "Custom"
                text_color: 0.06, 0.11, 0.26, 1
                pos_hint: {"center_y": .5}

        # --- ส่วนกล่องช่องค้นหา (Search Bar) ---
        MDCard:
            size_hint_y: None
            height: "72dp"
            md_bg_color: 1, 1, 1, 1
            radius: [12, 12, 12, 12]
            elevation: 0
            line_color: 0.8, 0.8, 0.8, 1
            padding: ["16dp", "0dp", "16dp", "0dp"]

            MDTextField:
                id: search_field
                hint_text: "พิมพ์ค้นหาด้วยชื่อ, นามสกุล หรืออีเมลพนักงาน..."
                icon_left: "magnify"
                pos_hint: {"center_y": .5}
                on_text: root.load_users_from_db(self.text)
                active_line: False
                line_color_normal: 0, 0, 0, 0
                line_color_focus: 0, 0, 0, 0

        # --- พื้นที่แสดงรายชื่อพนักงาน ---
        MDCard:
            md_bg_color: 1, 1, 1, 1
            radius: [16, 16, 16, 16]
            elevation: 2
            shadow_softness: 24  # ดันเงาให้หนาละมุนเหมือนหน้าเบิกยา
            padding: "12dp"

            MDBoxLayout:
                orientation: "vertical"

                # หัวตารางจำลอง
                MDBoxLayout:
                    size_hint_y: None
                    height: "36dp"
                    padding: ["16dp", "0dp"]
                    MDLabel:
                        text: "รายชื่อพนักงานในระบบตู้ล็อกเกอร์"
                        bold: True
                        theme_text_color: "Secondary"

                # รายการเลื่อนดู
                MDScrollView:
                    MDList:
                        id: employee_list
                        spacing: "8dp"