#: import get_color_from_hex kivy.utils.get_color_from_hex
#: set LIGHT_BG get_color_from_hex("#F7F8FC")
#: set RED_COLOR get_color_from_hex("#E74C3C")

<QRScanScreen@MDScreen>:
    name: "qr_scan_screen"
    md_bg_color: LIGHT_BG

    on_leave:
        qr_token_input.focus = False
        qr_token_input.text = ""

    MDBoxLayout:
        orientation: "vertical"
        padding: "24dp"
        spacing: "18dp"

        MDLabel:
            text: "ทำรายการผ่าน QR Code"
            halign: "center"
            font_style: "H5"

        MDLabel:
            text: "กรุณาสแกนหรือวาง QR token เพื่อดึงรายการที่ได้รับมอบหมาย"
            halign: "center"
            theme_text_color: "Secondary"

        Widget:

        MDCard:
            size_hint: None, None
            size: "700dp", "170dp"
            pos_hint: {"center_x": 0.5}
            padding: "20dp"
            md_bg_color: 1, 1, 1, 1

            MDBoxLayout:
                orientation: "vertical"
                spacing: "12dp"

                MDBoxLayout:
                    size_hint_y: None
                    height: "50dp"
                    md_bg_color: get_color_from_hex("#E8ECEF") # สีพื้นหลังเทาอ่อนให้ดูคล้ายช่องกรอก
                    radius: [8, 8, 8, 8]
                    padding: "10dp"

                    MDLabel:
                        id: qr_token_input
                        text: "--- กรุณาสแกน QR Code ---"
                        halign: "center"
                        font_style: "Subtitle1"
                        theme_text_color: "Custom"
                        text_color: get_color_from_hex("#2C3E50")

                MDRectangleFlatButton:
                    text: "ตรวจสอบ QR"
                    line_color: get_color_from_hex("#11cd3d")
                    theme_text_color: "Custom"
                    text_color: get_color_from_hex("#11cd3d")
                    pos_hint: {"center_x": 0.5}
                    on_release: app.handle_qr_submit(qr_token_input.text)

        Widget:

        MDBoxLayout:
            adaptive_height: True
            spacing: "12dp"
            pos_hint: {"center_x": 0.5}

            MDRectangleFlatButton:
                text: "CANCEL"
                line_color: RED_COLOR
                theme_text_color: "Custom"
                text_color: RED_COLOR
                on_release: app.change_screen("home_screen")